import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';
import { QueryProviders } from './providers/QueryProviders';
import { Providers } from './store/provider';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const ArchivoFont = Archivo({
  subsets: ['latin'],
  weight: ['100', '400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ArchivoFont.className} antialiased`}>
        <Providers>
          <QueryProviders>
            {children}
            <Toaster />
          </QueryProviders>
        </Providers>
      </body>
    </html>
  );
}
